# Generated by Django 5.2.2 on 2025-06-21 08:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('set_main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listingmod',
            name='features',
        ),
        migrations.CreateModel(
            name='FeaturesMod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('features', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='set_main.featurescat')),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='set_main.listingmod')),
            ],
        ),
    ]
