# Generated by Django 5.2.3 on 2025-07-01 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('set_main', '0002_remove_listingmod_features_featuresmod'),
    ]

    operations = [
        migrations.CreateModel(
            name='NearbyMod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='listingmod',
            name='bathrooms',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listingmod',
            name='documents_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listingmod',
            name='floor',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listingmod',
            name='furnished',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listingmod',
            name='mortgage_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listingmod',
            name='parking',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listingmod',
            name='toilets',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listingmod',
            name='transaction_type',
            field=models.CharField(blank=True, choices=[('rent', 'Аренда'), ('sale', 'Продажа')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='featuresmod',
            name='features',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='set_main.featurescat'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='NearbyListMod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='set_main.listingmod')),
                ('nearby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='set_main.nearbymod')),
            ],
        ),
    ]
