# Generated by Django 5.2.3 on 2025-07-05 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('set_main', '0003_nearbymod_listingmod_bathrooms_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='email',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='username',
        ),
        migrations.RemoveField(
            model_name='listingmod',
            name='documents_verified',
        ),
        migrations.RemoveField(
            model_name='listingmod',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='customuser',
            name='language',
            field=models.CharField(choices=[('ru', 'Russian'), ('en', 'English'), ('uz', 'Uzbek')], default='ru', max_length=3),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(default=1, max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='listingmod',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
