# Generated by Django 5.2.3 on 2025-07-15 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('set_main', '0005_rename_phone_number_customuser_phone_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phoneconfirmation',
            name='expires_at',
        ),
        migrations.RemoveField(
            model_name='phoneconfirmation',
            name='user',
        ),
        migrations.AddField(
            model_name='phoneconfirmation',
            name='phone',
            field=models.CharField(default=1, max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
