# Generated by Django 5.1.2 on 2025-07-16 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('set_main', '0006_remove_phoneconfirmation_expires_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listingmod',
            name='transaction_type',
            field=models.CharField(blank=True, choices=[('rent', 'Аренда'), ('sale', 'Продажа')], max_length=50, null=True),
        ),
    ]
