# Generated by Django 5.2.3 on 2025-07-17 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('set_main', '0008_alter_listingmod_transaction_type_delete_commentmod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listingmod',
            name='transaction_type',
            field=models.CharField(blank=True, choices=[('rent', 'Аренда'), ('sale', 'Продажа')], max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='CurrencyRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(choices=[('USD', '🇺🇸 Доллар США'), ('RUB', '🇷🇺 Российский рубль'), ('UZS', '🇺🇿 Сум (базовая валюта)')], max_length=3)),
                ('rate', models.DecimalField(decimal_places=4, max_digits=12)),
                ('date', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Курс валюты',
                'verbose_name_plural': 'Курсы валют',
                'unique_together': {('currency', 'date')},
            },
        ),
    ]
