# Generated by Django 5.2.3 on 2025-07-17 09:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('set_main', '0009_alter_listingmod_transaction_type_currencyrate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listingmod',
            old_name='price_rub',
            new_name='price',
        ),
        migrations.RemoveField(
            model_name='listingmod',
            name='price_usd',
        ),
        migrations.RemoveField(
            model_name='listingmod',
            name='price_uzs',
        ),
        migrations.AddField(
            model_name='listingmod',
            name='currency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='set_main.currencyrate'),
        ),
        migrations.AlterField(
            model_name='listingmod',
            name='transaction_type',
            field=models.CharField(blank=True, choices=[('sale', 'Продажа'), ('rent', 'Аренда')], max_length=50, null=True),
        ),
    ]
