# Generated by Django 5.2.3 on 2025-07-17 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('set_main', '0010_rename_price_rub_listingmod_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listingmod',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='listingmod',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='listingmod',
            name='types',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='set_main.typesell', verbose_name='Тип недвижимости'),
        ),
    ]
